### ISSUE TITLE
Import local files

### ISSUE THREAD

**Issue by joscdk** [mxcl/swift-sh#17]
This is a really great package!.. I was thinking (if possible) being able to include local files would be a big help

e.g.:

**test1.swift**
```swift
#!/usr/bin/swift sh
import Foobar // ./test2.swift

print(Foobar().foo())
```

**test2.swift**
```swift
final class Foobar {
	init() {

	}

	func foo() -> String {
		return "Foobar!"
	}
}
```

Not sure if it's even possible to do, but would allow to create a bit more advanced scripts with this :)

**Comment by mxcl** [comment]
I wasn't indeed thinking about this too. Each local file would have to be a separate module. We could possibly make it so folders full of swift files were treated as modules.

**Comment by mxcl** [comment]
My main concern is that at this point maybe you should just use SwiftPM, I know that the syntax for `Package.swift` is unpleasant nowadays… but still.

**Comment by joscdk** [comment]
Yeah you might be right about using SwiftPM :) 

Was thinking this *could* be a nice alternative to writing simple ruby scripts, where you just have a couple of files to build a small migration script, but might be the right way to do SwiftPM

**Comment by mattt** [comment]
As much as I appreciate the convenience of importing a local `.swift` file _a la_ Ruby, I think the nature of Swift modules makes this approach untenable. 

For one, I don't think the example above would actually work because `Foo` and its members aren't declared with `public` access. Please don't take that as a personal knock, @joscdk --- I routinely run into problems caused by a missing `public` in my own code (especially code in the `Sources` directory for Xcode Playgrounds). And I suspect many other folks would be flummoxed by this more often than not.

Aside from that, I worry about the logistics of managing external files as implicit modules. 
_How do you detect changes?_ 
_How do you reconcile namespace collisions and shadowed declarations?_
_How do you handle dependency cycles?_
None of these are too hard individually, but in sum they amount to essentially recreating a good portion of package manager functionality.

**Comment by joscdk** [comment]
@mattt yeah i see your point, this might be something that might be possible later as Swift matures as a language :)

**Comment by mxcl** [comment]
SwiftPM is a better solution for this, and something like Xcode on top would make managing your modularity better.

**Comment by davbeck** [comment]
SwiftPM probably is the right answer in most cases, but something that I ran into recently is a script used as part of a larger project (ie something that downloads resources that are then bundled into an app). In this case it makes sense to pull in a file or 2 from the primary project. For instance, the script may need to process some data and then write out a JSON file. The app of course is going to read the same file. In this case it makes sense for the app and the script to share the Codable models.

What if there was an include comment that pulled in single files to the same module?

`// include Models.swift`
Or
`// include ../App/Models.swift`

**Comment by mxcl** [comment]
Yeah, my mind has changed. I have needed such things.
